myapp/urls.py
from django.urls import path ,include
from rest_framework.routers import DefaultRouter

from myapp.views import *

from django.conf import settings
from django.conf.urls.static import static

from django.contrib.auth.views import LoginView, logout_then_login ,LogoutView



app_name = "myapp"
urlpatterns = [

    path('', CustomLoginView.as_view(), name='login'),
    path('registro/', post_registro, name='hacer_registro'),
    path('cliente/registro/', post_registro_cliente, name='hacer_registro_cliente'),


    path('logout/', LogoutView.as_view(), name='logout'),

    # DetalleGenerico
    path('detalle/<str:tipo_objeto>/<int:id_objeto>/', login_required(DetalleGenericoView.as_view()), name='detalle_generico'),


    path('historial/pedidos/restaurante/<int:restaurante_id>', login_required(ListPedidosAdmin.as_view()), name='historial_pedidos_restaurante'),
    #restaurante
    path('lista/restaurantes/', login_required(ArticleDetailView.as_view()), name='list_restaurantes'),
    path('anadir/restaurante/', login_required(post_add_restaurante), name='add_restaurante'),

    #user_repartidor_cocina
    path('anadir/trabajdor/repartidor/<int:restaurante_id>', login_required(add_user_reparidor), name='add_user_reparidor'  ),
    path('anadir/trabajdor/cocina/<int:restaurante_id>', login_required(add_user_cocina), name='add_user_cocina'  ),

    path('lista/trabajdores/<int:restaurante_id>', login_required(UsuariosRestauranteListView.as_view()), name='list_user_restaurant'),

    path('reset_password/<int:user_id>/<int:restaurante_id>/', login_required(reset_password), name='reset_password'),
    path('denegar_acceso/<int:user_id>/<int:restaurante_id>/', login_required(denegar_acceso), name='denegar_acceso'),
    #platos
    path('restaurante/agregar_plato/<int:restaurante_id>/', login_required(agregar_plato), name='agregar_plato'),
    path('restaurante/listar_plato/<int:restaurante_id>/', login_required(PlatosRestauranteListView.as_view()) , name='list_platos'),

    # resena
    path('resena/<str:tipo_objeto>/<int:id_objeto>/',  login_required(ResenasView.as_view()), name='resena_generico'),
    path('resena/crear/<str:tipo_objeto>/<int:id_objeto>/', login_required(crear_resena), name='crear_una_resena'),

    path('resena/<str:tipo_objeto>/<int:id_objeto>/admin/',  login_required(ResenasAdminView.as_view()), name='resena_generico_admin'),

    path('resenas/<str:tipo_objeto>/<int:id_objeto>/borrar/<int:pk>/', login_required(BorrarResenaView.as_view()), name='borrar_resena'),

    #horarios res
    path('restaurante/add_horarios/<int:restaurante_id>/', login_required(add_horarios), name='add_horarios'),



    #admins
    path('lista/partners', PartnersListView.as_view(),  name='list_partners' ),
    path('acces/partners/<int:id_user>/', active_partners,name='active_partners'),


    #cliente
    path('cliente/lista/restaurantes/', login_required(RestauranteListClienteView.as_view()), name='restaurantes_list_cliente'),
    path('cliente/lista/restaurante/<int:restaurante_id>/platos/', login_required(PlatosListClienteView.as_view()), name='platos_list_cliente'),


    #cliente-carito
    path('agregaralcarrito/<int:plato_id>/', login_required(agregar_al_carrito), name='agregar_carrito'),
    path('carrito/',  login_required(carrito_lista), name='pagina_del_carrito'),
    path('quitar_plato_carrito/<int:plato_id>/', login_required(quitar_plato_carrito),
         name='quitar_plato_carrito'),

    path('eliminar/plato/carrito/<int:plato_id>/',  login_required(eliminar_plato_carrito), name='eliminar_plato_carrito'),
    path('carrito/borrar/', login_required(borrar_carrito), name='borrar_carrito'),

    #pedidos
    path('pedidos_realizados/', login_required(Pedidos_realizadosView.as_view()) , name='pedidos_realizados'),
    path('pedido/<int:pedido_id>/cancelar/', login_required(cancelar_pedido), name='cancelar_pedido'),
    path('procesar_pedido/form/', login_required(procesar_pedido_from), name='procesar_pedido_form'),



    #cocina
    path('pedidos_actualizados/', login_required(ListPedidosCocina.as_view()), name='pedidos_actualizados'),
    path('pedido/<int:pedido_id>/preparacion/', login_required(preparacion_pedido), name='preparacion_pedido'),
    path('asignar_repartidor/<int:pedido_id>', asignar_repartidor, name='asignar_repartidor'),

    #repartidor
    path('pedidos/para/<str:tipo_objeto>/', login_required(ListPedidosRepartidor.as_view()), name='pedidos_repartidor'),
    #path('pedidos/para/entregar/', login_required(ListPedidosRepartidor.as_view()), name='pedidos_para_entregar'),
    #path('pedidos/entregados/', login_required(ListPedidosParaRecoger.as_view()), name='pedidos_para_recoger'),
    path('pedidos/<int:pedido_id>/recoger_pedido/', login_required(recoger_pedido), name='recoger_pedido'),
    path('pedido/<int:pk>/map', login_required(Map_Rpartidor.as_view()), name='map_rpartidor'),
    path('pedidos/<int:pedido_id>/validar_pedido/', login_required(validar_pedido), name='validar_pedido'),


    path('generar/<int:id_objeto>/<str:tipo_objeto>/pdf', login_required(Generar_pdf.as_view()),name='generar_pdf'),

    path('estado_pedido/<int:pedido_id>/actualizo/', EstadoPedidoActualizado.as_view(), name='estado_pedido_actualizado'),


]

# Agregar la configuracion para servir archivos de medios
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# add Configuring static files
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

sistemdelivereat/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('myapp.urls')),

]

# Agregar la configuracion para servir archivos de medios

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# add Configuring static files
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

myapp/views/cliente.py
from datetime import datetime
from decimal import Decimal

import stripe
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.paginator import Paginator
from django.db import transaction
from django.db.models import Avg, Q, Subquery, OuterRef, Sum
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import ListView, DetailView
from django.db.models import F, ExpressionWrapper, DecimalField
from django.db.models.functions import Round, Cast
from myapp.models import Restaurante, Plato, Cliente, Pedido, Ubicacion, TipoComida, PedidoPlato
from sistemdelivereat.utils.OpenStreetMap import Geocoder
from sistemdelivereat.utils.RolRequiredMixin import RolRequiredMixin
from sistemdelivereat.utils.carito_copras import CarritoDeCompras
from sistemdelivereat.utils.decorators import web_access_type_required
from django.contrib.auth.decorators import login_required

from django.contrib import messages

stripe.api_key = 'sk_test_51PMYfiGF2SGr9v2Ept70FwVCMRnjM8pdznzqezNqqxb3nmOx2xKFV9tezdmUONwHliygMlXXIFejCtvSdaIs2Hmg00AbvQ91MU'


class RestauranteListClienteView(LoginRequiredMixin, RolRequiredMixin, ListView):
    model = Restaurante
    user_type_required = ['cliente']
    template_name = 'cliente/lista_restaurantes.html'
    context_object_name = 'restaurantes'
    paginate_by = 10

    def get_queryset(self):
        cliente_ciudad=get_object_or_404(Cliente, user=self.request.user).ubicacion.ciudad
        restaurantes = Restaurante.objects.filter(ubicacion__ciudad=cliente_ciudad).annotate(
            puntuacion_media=Avg('resenas__puntuacion')
        ).order_by('-puntuacion_media')



        query = self.request.GET.get('query')

        if query:
            restaurantes = restaurantes.filter(
                Q(nombre=query) |
                Q(ubicacion__direcion__icontains=query)

            )
        return restaurantes

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context['title_pagina'] = {'label_title': "Llistado de restaurantes",
                                   'title_card': "Llistado de restaurantes " ,
                                   },



        return context


class PlatosListClienteView(LoginRequiredMixin, RolRequiredMixin, ListView):
    model = Plato
    user_type_required = ['cliente']
    template_name = 'cliente/lista_platos.html'
    context_object_name = 'platos'
    paginate_by = 10


    def get_queryset(self):
        restaurante_id = self.kwargs['restaurante_id']

        order_by = self.request.GET.get('order_by')
        order_direction = self.request.GET.get('order_direction')
        precio_min = self.request.GET.get('precio_min')
        precio_max = self.request.GET.get('precio_max')

        if precio_min and precio_max:
            try:
                precio_min = float(precio_min)
                precio_max = float(precio_max)
                if precio_min > precio_max:
                    messages.error(self.request, 'El precio mínimo no puede ser mayor que el precio máximo.')
                    return Plato.objects.none()
            except ValueError:
                messages.error(self.request, 'Los valores de precio deben ser números válidos.')
                return Plato.objects.none()

        platos = Plato.objects.filter(restaurante_id=restaurante_id).annotate(
            puntuacion_media=Avg('resenas__puntuacion'),
            precio_final=(F('precio') - (F('precio') * F('descuento') / 100))
        )

        if order_by == "precio":
            if order_direction == "asc":
                platos = platos.order_by('precio_final')
            elif order_direction == "desc":
                platos = platos.order_by('-precio_final')
        else:
            platos = platos.order_by('-puntuacion_media')

        if precio_min:
            platos = platos.filter(precio_final__gte=precio_min)
        if precio_max:
            platos = platos.filter(precio_final__lte=precio_max)

        query = self.request.GET.get('query')
        tipo_comida = self.request.GET.get('tipo_comida')
        if query:
            platos = platos.filter(
                Q(nombre__icontains=query)

            )
        if tipo_comida:
            platos = platos.filter(
                Q(tipo_comida__nombre=tipo_comida)

            )
        return platos


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Obtén el ID del restaurante de la URL
        restaurante_id = self.kwargs['restaurante_id']

        context['tipos_comida'] = TipoComida.objects.filter(platos_tipo_comida__in=self.get_queryset()).distinct()

        # Obtén el restaurante
        restaurante = Restaurante.objects.get(pk=restaurante_id)

        context['title_pagina'] = {'label_title': "Llistat de platos",
                                   'title_card': "Llistat de platos de " + restaurante.nombre,
                                   },
        context['ruta_pagina'] = [{
            'text': "Lista de restaurantes",
            'link': "myapp:restaurantes_list_cliente",
        },
            {
                'text': "Lista de los platos  de " + restaurante.nombre,
                'link': "",
            }
        ]
        context['restaurante_id'] = restaurante.id
        return context

def descuento(plato):
    precio_con_descuento = plato.precio * (1 - Decimal(str(plato.descuento)) / 100)
    return precio_con_descuento.quantize(Decimal('0.00'))
def tax(precio):
    precio_con_tax = precio + ((precio * 10 ) / 100 ) + ((precio * 3 ) / 100 )
    return precio_con_tax.quantize(Decimal('0.00') + Decimal('0.50') )
@login_required
@web_access_type_required("cliente")
def agregar_al_carrito(request, plato_id):
    carrito = CarritoDeCompras(request)
    carrito.agregar_plato(str(plato_id))
    return redirect(request.META.get('HTTP_REFERER', '/'))


@login_required
@web_access_type_required("cliente")
def carrito_lista(request):
    carrito = CarritoDeCompras(request).obtener_carrito()
    platos_en_carrito = Plato.objects.filter(id__in=carrito.keys())


    # Verificar si el carrito está vacío
    if not platos_en_carrito:
        total_formateado = Decimal('0.00')
        totales_por_restaurante = {}
    else:
        # Calcular el total por restaurante
        totales_por_restaurante = {}
        for plato in platos_en_carrito:
            restaurante_id = plato.restaurante.id
            plato_id = str(plato.id)
            cantidad = carrito.get(plato_id, {'cantidad': 0})['cantidad']
            precio_final = descuento(plato)

            if restaurante_id not in totales_por_restaurante:
                totales_por_restaurante[restaurante_id] = {
                    'nombre': plato.restaurante.nombre,
                    'total': 0
                }

            totales_por_restaurante[restaurante_id]['total'] += cantidad * precio_final

        # Calcular el total general
        total_general = sum(tax(restaurante['total']) for restaurante in totales_por_restaurante.values())
        total_formateado = Decimal(str(total_general)).quantize(Decimal('0.01'))

    # Crear un diccionario para almacenar las cantidades de cada plato en el carrito
    cantidades_por_plato = {}
    for plato in platos_en_carrito:
        plato_id = str(plato.id)
        cantidad = carrito.get(plato_id, {'cantidad': 0})['cantidad']
        cantidades_por_plato[plato_id] = cantidad


    title_pagina = [
        {'label_title': "Carrito de compras",
         'title_card': "Carrito de compras "}
    ]
    ruta_pagina = [
        {'text': "Lista de restaurantes", 'link': "myapp:restaurantes_list_cliente"},
        {'text': "Carrito de compras", 'link': ""}
    ]

    return render(request, 'cliente/carito/carrito_lista.html', {
        'platos': platos_en_carrito,
        'cantidades_por_plato': cantidades_por_plato,
        'total': total_formateado,
        'totales_por_restaurante': totales_por_restaurante,
        'title_pagina': title_pagina,
        'ruta_pagina': ruta_pagina,
    })
@login_required
@web_access_type_required("cliente")
def eliminar_plato_carrito(request, plato_id):
    carrito = CarritoDeCompras(request)
    carrito.eliminar_plato(str(plato_id))
    return redirect('myapp:pagina_del_carrito')


@login_required
@web_access_type_required("cliente")
def quitar_plato_carrito(request, plato_id):
    carrito = CarritoDeCompras(request)
    carrito.quitar_plato(str(plato_id))
    return redirect('myapp:pagina_del_carrito')


@login_required
@web_access_type_required("cliente")
def borrar_carrito(request):
    carrito = CarritoDeCompras(request)
    carrito.borrar_carrito()
    return redirect('myapp:pagina_del_carrito')





class Pedidos_realizadosView(LoginRequiredMixin, RolRequiredMixin, ListView):
    model = Pedido
    user_type_required = ['cliente']
    template_name = 'cliente/pedido/listado_pedidos.html'
    context_object_name = 'pedidos'
    paginate_by = 10


    def get_queryset(self):
        page_number = self.request.GET.get('page', 2)
        pedidos = Pedido.objects.filter(cliente=Cliente.objects.get(user = self.request.user )).order_by('-fecha_pedido')
        query = self.request.GET.get('query')
        estado_pedido = self.request.GET.get('estado')
        restaurante = self.request.GET.get('restaurante')
        data_inicio = self.request.GET.get('data_inicio')
        data_fin = self.request.GET.get('data_fin')

        if query:
            pedidos = pedidos.filter(
                Q(platos__nombre__icontains=query)
                # Q(codigo_pedido=query)
            )
        if estado_pedido:
            pedidos = pedidos.filter(
                Q(estado=estado_pedido)
            )
        if restaurante:
            pedidos = pedidos.filter(
                Q(restaurante_id=restaurante)
            )
        if data_inicio and data_fin:

templates/cliente/lista_platos.html
{% extends 'base/base_adminlte.html' %}
{% load static %}
{% block style %}
 <link rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="{% static 'adminlte/css/all.min.css' %}">
    <!--  iconas fas -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css"
          integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">

    <link rel="stylesheet" href="{% static 'adminlte/css/adminlte.min.css' %}">
{% endblock %}

{% block content %}

<div class="content">
<div class="container">

  {% if messages %}
      {% for message in messages %}
      <div {% if message.tags %} class="alert alert-{% if message.tags == 'error' %}danger{% else %}{{ message.tags }}{% endif %} alert-dismissible" {% endif %}>
      <button  type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <h5><i class="icon fas fa-check"></i> {{ message.tags }}</h5>
      {{ message }}
   </div>
   {% endfor %}
   {% endif %}

  <div class="row">
  
   <div class="col-md-12">
        <form action="" method="get"  name="prodsubmit" >
            <div class="input-group mb-3">

                 <div class="input-group-prepend">
                    <button class="btn btn-outline-secondary dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Ordenar por </button>
                    <div class="dropdown-menu">


                          <a class="dropdown-item" href="{% url 'myapp:platos_list_cliente' restaurante_id=restaurante_id  %}?order_by=precio&order_direction=desc"> Precio <i class="fas fa-arrow-up mr-1 float-right"></i>  </a>
                        <a class="dropdown-item" href="{% url 'myapp:platos_list_cliente' restaurante_id=restaurante_id  %}?order_by=precio&order_direction=asc"> Precio <i class="fas fa-arrow-down mr-1 float-right"></i>  </a>
                         <a class="dropdown-item" href="{% url 'myapp:platos_list_cliente' restaurante_id=restaurante_id  %}"> Puntuación <i class="fas fa-arrow-up mr-1 float-right"></i>  </a>
                      </div>
                    </div>

                 <div class="input-group-prepend">
                    <button class="btn btn-outline-secondary dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Filtrar por precios </button>
                    <div class="dropdown-menu">
                          <div class="p-2">
<div class="input-group-prepend">
    Precio desde
</div>
<input type="number" name="precio_min" class="form-control" placeholder="Precio mínimo" value="{{ request.GET.precio_min }}"  min="1" max="999">

<div class="input-group-prepend">
   Precio hasta
</div>
<input type="number" name="precio_max" class="form-control" placeholder="Precio máximo" value="{{ request.GET.precio_max }}"  min="1" max="999" >
<br>
                         <a href="javascript:document.prodsubmit.submit()" style="text-decoration:none;">
                    <span class="input-group-text" id="basic-addon1">Buscar</span>
                  </a>
 </div>
                      </div>
                    </div>
                
                 <div class="input-group-prepend">
                    <button class="btn btn-outline-secondary dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Filtrar por tipos </button>
                    <div class="dropdown-menu">
                        {% for tipos in tipos_comida %}

                          <a class="dropdown-item" href="{% url 'myapp:platos_list_cliente' restaurante_id=restaurante_id  %}?tipos={{ tipos.nombre }}"> {{ tipos.nombre }} </a>
                         {% endfor %}
                    
                        <div role="separator" class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{% url 'myapp:platos_list_cliente' restaurante_id=restaurante_id %}">Mostrar todo</a>
                      </div>
                    </div>

                  <input type="text" name="query" class="form-control" placeholder="Buscar ... " value="{{ request.GET.query }}" autocomplete="off">
                  <a href="javascript:document.prodsubmit.submit()" style="text-decoration:none;">
                    <span class="input-group-text" id="basic-addon1">Buscar</span>
                  </a>

             </div>
        </form>

       </div>
  
    <div class="col-md-12">
<div class="card">
    <div class="card-body">
             {% if platos %}
          {% for plato in platos %}
        <div class="post clearfix">
<div class="user-block" >
<img class="img-circle img-bordered-sm" src="{{ plato.imagen.url }}" alt="Imagen de {{ plato.nombre }}">
<span class="username">
<a href="#">{{ plato.nombre }} </a>
<div class="float-right ">

     <div class="estrellas" data-puntuacion=" {{ plato.puntuacion_media }}"></div>
</div>

</span>
<span class="description">

     {% if plato.descuento > 0 %}
             <h5> <del>{{ plato.precio }}</del> -  {{ plato.precio_final }}  €</h5>

            {% else %}
                 <h5>{{ plato.precio }}  €  </h5>
            {% endif %}
        
    <small class="badge " style="background-color: #F49941; color:white"> {{ plato.tipo_comida.nombre }} </small>


</span>

</div>


<ul>
{% for ingrediente in plato.ingredientes.all %}
                  <li> {{ ingrediente.nombre }}</li>
                   {% endfor %}
</ul>
<p>
<a href="{% url 'myapp:resena_generico' tipo_objeto='plato' id_objeto=plato.id %}" class="link-black text-sm">
<i class="far fa-comments mr-1"></i> Reseñas ({{ plato.resenas.count }})
</a>


<span class="float-right"> 
<a href="{% url 'myapp:agregar_carrito' plato_id=plato.id %}">Agregar al carrito</a>

</span>
</p>



</div>
            
          {% endfor %}
    
                    {% else %}
                     <p> No hay ningún plato de momento. </p>
                     {% endif%}
    
            
    
    
    
     </div>
 <div class="card-footer">
       <ul class="pagination pagination-sm d-flex justify-content-center">
                        {% if is_paginated %}
                        {% if page_obj.has_previous %}
                        <li class="page-item">
                           <a class="page-link" href="?page=1">&laquo;</a>
                        </li>
                        <li class="page-item">
                           <a class="page-link" href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a>
                        </li>
                        {% endif %}
                        <li class="page-item active">
                           <a class="page-link" href="?page={{ page_obj.number }}">{{ page_obj.number }}</a>
                        </li>
                        {% if page_obj.has_next %}
                        <li class="page-item">
                           <a class="page-link" href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a>
                        </li>
                        <li class="page-item">
                           <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">&raquo;</a>
                        </li>
                        {% endif %}
                        {% else %}
                        <li class="page-item"><a class="page-link" href="#">&laquo;</a></li>
                        <li class="page-item"><a class="page-link" href="#">1</a></li>
                        <li class="page-item"><a class="page-link" href="#">&raquo;</a></li>
                        {% endif %}
                     </ul>
  </div>
  </div>
        </div>

</div>





</div>
</div>


{% endblock %}



{% block script %}



    <script>
    function dibujarEstrellas(elemento) {
         const puntuacion = parseFloat(elemento.getAttribute('data-puntuacion'));
        // Tu código para dibujar las estrellas
        const totalEstrellas = 5;
        const estrellasLlenas = Math.floor(puntuacion);
        const estrellaParcial = puntuacion - estrellasLlenas;
        const estrellasVacias = totalEstrellas - estrellasLlenas - (estrellaParcial > 0 ? 1 : 0);
        let estrellasHtml = '';

        for (let i = 0; i < estrellasLlenas; i++) {
            estrellasHtml += '<i class="fas fa-star mr-1 text-warning"></i>';
        }

         if (estrellaParcial > 0) {
            estrellasHtml += '<i class="fas fa-star-half-alt mr-1 text-warning"></i>';
        }

        for (let i = 0; i < estrellasVacias; i++) {
            estrellasHtml += '<i class="far fa-star mr-1 text-warning"></i>';
        }

        // Agregar el HTML generado al elemento
        elemento.innerHTML = estrellasHtml;
    }

    // Seleccionar todos los elementos con la clase 'estrellas'
    const elementosEstrellas = document.querySelectorAll('.estrellas');

    // Iterar sobre los elementos seleccionados y llamar a la función dibujarEstrellas
    elementosEstrellas.forEach(function(elemento) {
        dibujarEstrellas(elemento);
    });

    </script>

<!-- jQuery -->
<script src="{% static 'adminlte/js/jquery.min.js' %}"></script>
<!-- Bootstrap 4 -->
<script src="{% static 'adminlte/js/bootstrap.bundle.min.js' %}"></script>
<!-- AdminLTE App -->
<script src="{% static 'adminlte/js/adminlte.min.js' %}"></script>

{% endblock %}