myapp/urls.py
from django.urls import path ,include
from rest_framework.routers import DefaultRouter

from myapp.views import *

from django.conf import settings
from django.conf.urls.static import static

from django.contrib.auth.views import LoginView, logout_then_login ,LogoutView



app_name = "myapp"
urlpatterns = [

    path('', CustomLoginView.as_view(), name='login'),
    path('registro/', post_registro, name='hacer_registro'),
    path('cliente/registro/', post_registro_cliente, name='hacer_registro_cliente'),


    path('logout/', LogoutView.as_view(), name='logout'),

    # DetalleGenerico
    path('detalle/<str:tipo_objeto>/<int:id_objeto>/', login_required(DetalleGenericoView.as_view()), name='detalle_generico'),


    path('historial/pedidos/restaurante/<int:restaurante_id>', login_required(ListPedidosAdmin.as_view()), name='historial_pedidos_restaurante'),
    #restaurante
    path('lista/restaurantes/', login_required(ArticleDetailView.as_view()), name='list_restaurantes'),
    path('anadir/restaurante/', login_required(post_add_restaurante), name='add_restaurante'),

    #user_repartidor_cocina
    path('anadir/trabajdor/repartidor/<int:restaurante_id>', login_required(add_user_reparidor), name='add_user_reparidor'  ),
    path('anadir/trabajdor/cocina/<int:restaurante_id>', login_required(add_user_cocina), name='add_user_cocina'  ),

    path('lista/trabajdores/<int:restaurante_id>', login_required(UsuariosRestauranteListView.as_view()), name='list_user_restaurant'),

    path('reset_password/<int:user_id>/<int:restaurante_id>/', login_required(reset_password), name='reset_password'),
    path('denegar_acceso/<int:user_id>/<int:restaurante_id>/', login_required(denegar_acceso), name='denegar_acceso'),
    #platos
    path('restaurante/agregar_plato/<int:restaurante_id>/', login_required(agregar_plato), name='agregar_plato'),
    path('restaurante/listar_plato/<int:restaurante_id>/', login_required(PlatosRestauranteListView.as_view()) , name='list_platos'),

    # resena
    path('resena/<str:tipo_objeto>/<int:id_objeto>/',  login_required(ResenasView.as_view()), name='resena_generico'),
    path('resena/crear/<str:tipo_objeto>/<int:id_objeto>/', login_required(crear_resena), name='crear_una_resena'),

    path('resena/<str:tipo_objeto>/<int:id_objeto>/admin/',  login_required(ResenasAdminView.as_view()), name='resena_generico_admin'),

    path('resenas/<str:tipo_objeto>/<int:id_objeto>/borrar/<int:pk>/', login_required(BorrarResenaView.as_view()), name='borrar_resena'),

    #horarios res
    path('restaurante/add_horarios/<int:restaurante_id>/', login_required(add_horarios), name='add_horarios'),



    #admins
    path('lista/partners', PartnersListView.as_view(),  name='list_partners' ),
    path('acces/partners/<int:id_user>/', active_partners,name='active_partners'),


    #cliente
    path('cliente/lista/restaurantes/', login_required(RestauranteListClienteView.as_view()), name='restaurantes_list_cliente'),
    path('cliente/lista/restaurante/<int:restaurante_id>/platos/', login_required(PlatosListClienteView.as_view()), name='platos_list_cliente'),


    #cliente-carito
    path('agregaralcarrito/<int:plato_id>/', login_required(agregar_al_carrito), name='agregar_carrito'),
    path('carrito/',  login_required(carrito_lista), name='pagina_del_carrito'),
    path('quitar_plato_carrito/<int:plato_id>/', login_required(quitar_plato_carrito),
         name='quitar_plato_carrito'),

    path('eliminar/plato/carrito/<int:plato_id>/',  login_required(eliminar_plato_carrito), name='eliminar_plato_carrito'),
    path('carrito/borrar/', login_required(borrar_carrito), name='borrar_carrito'),

    #pedidos
    path('pedidos_realizados/', login_required(Pedidos_realizadosView.as_view()) , name='pedidos_realizados'),
    path('pedido/<int:pedido_id>/cancelar/', login_required(cancelar_pedido), name='cancelar_pedido'),
    path('procesar_pedido/form/', login_required(procesar_pedido_from), name='procesar_pedido_form'),



    #cocina
    path('pedidos_actualizados/', login_required(ListPedidosCocina.as_view()), name='pedidos_actualizados'),
    path('pedido/<int:pedido_id>/preparacion/', login_required(preparacion_pedido), name='preparacion_pedido'),
    path('asignar_repartidor/<int:pedido_id>', asignar_repartidor, name='asignar_repartidor'),

    #repartidor
    path('pedidos/para/<str:tipo_objeto>/', login_required(ListPedidosRepartidor.as_view()), name='pedidos_repartidor'),
    #path('pedidos/para/entregar/', login_required(ListPedidosRepartidor.as_view()), name='pedidos_para_entregar'),
    #path('pedidos/entregados/', login_required(ListPedidosParaRecoger.as_view()), name='pedidos_para_recoger'),
    path('pedidos/<int:pedido_id>/recoger_pedido/', login_required(recoger_pedido), name='recoger_pedido'),
    path('pedido/<int:pk>/map', login_required(Map_Rpartidor.as_view()), name='map_rpartidor'),
    path('pedidos/<int:pedido_id>/validar_pedido/', login_required(validar_pedido), name='validar_pedido'),


    path('generar/<int:id_objeto>/<str:tipo_objeto>/pdf', login_required(Generar_pdf.as_view()),name='generar_pdf'),

    path('estado_pedido/<int:pedido_id>/actualizo/', EstadoPedidoActualizado.as_view(), name='estado_pedido_actualizado'),


]

# Agregar la configuracion para servir archivos de medios
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# add Configuring static files
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

sistemdelivereat/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('myapp.urls')),

]

# Agregar la configuracion para servir archivos de medios

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# add Configuring static files
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/base/base.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>{% block title %}{{ titulo_pagina }}{% endblock %}</title>
   <link rel="shortcut icon" href="/media/img/icono_app.ico" />
  <!--<link rel="stylesheet" href="css/style.css">-->
  {% block style %} {% endblock %}
</head>
<body>

 {% block content %}
     
 {% endblock %}

 
</body>
{% block script %}


{% endblock %}

</html>

templates/base/base_adminlte.html
<!DOCTYPE html>
{% load static %}
<head>
  <meta charset="UTF-8">
  <title>{% block title %}{{title_pagina.0.title_card}}{% endblock %}</title>
   <link rel="shortcut icon" href="/media/img/icono_app.ico" />
  <!--<link rel="stylesheet" href="css/style.css">-->
  {% block style %} {% endblock %}
     <link rel="stylesheet" href="{% static 'adminlte/css/custom.css' %}">

</head>
<body class="hold-transition layout-top-nav">
<div class="wrapper">


<nav class="main-header navbar navbar-expand-md navbar-light navbar-white" style="background-color: #F49941;">
 <!-- Left navbar links -->
{% if user.user_type == 'cliente' %}
    <ul class="navbar-nav">


<li class="nav-item d-none d-sm-inline-block" >    
     <a href="{% url 'myapp:restaurantes_list_cliente' %}" class="nav-link"  style="color: white">Restaurantes</a>
  </li>  
    <li class="nav-item d-none d-sm-inline-block" >
<a href="{% url 'myapp:pedidos_realizados' %}" class="nav-link"  style="color: white">Pedidos</a>
</li>
        </ul>
       {% endif %}


        <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <img src="/media/img/logo_menu.png" width="30px" height="30px" alt="logotipo menu"  >
            </li>


        </ul>

        <!-- Right navbar links -->
        <ul class="navbar-nav ml-auto">

            <!-- Messages Dropdown Menu -->

    {% if user.user_type == 'cliente' %}
    
            <li class="nav-item dropdown">
                <a class="nav-link" href="{% url 'myapp:pagina_del_carrito' %}">
                    <i class="fa fa-shopping-cart" style="color: white"></i>

 {% if total_carrito %}
         <span class="badge  navbar-badge" style="background-color: white; color:#F49941"> {{ total_carrito }} </span>
 {% endif %}



                   <!-- numero de las notifaciones -->
                </a>


            </li>
        
        {% endif %}
            <li class="nav-item dropdown">
                <a class="nav-link" data-toggle="dropdown" href="#" style="color: white">
                    {{ user.username }}
                </a>
                <div class="dropdown-menu dropdown-menu-lg dropdown-menu-lg">

                    <a href="#" class="dropdown-item">

                        <div class="media">
                           <img src="{{ user.get_img }}" alt="User Avatar {{ user.get_full_name }}"
                                 class="img-size-50 mr-3 img-circle">
                            <div class="media-body">
                                
                                
                                <h3 class="dropdown-item-title">
                                   {{ user.get_full_name }}
                                </h3>
                                <p class="text-sm"> {{ user.user_type }} </p>
                            </div>
                        </div>

                    </a>
                    <div class="dropdown-divider"></div>
                    <a href="#" class="dropdown-item dropdown">

                        <div class="media ">
                            <i class="fas fa-user-edit mr-1"></i>
                            <div class="media-body ">
                                <h3 class="dropdown-item-title ">
                                    Modificar les dades d'usuari
                                </h3>
                            </div>
                        </div>

                    </a>
                   <a href="#" id="logout-link" class="dropdown-item">
                        <div class="media">
                            <i class="fas fa-sign-out-alt mr-1"></i>
                            <div class="media-body">
                              <form action="{% url 'myapp:logout' %}" method="post">
  {% csrf_token %}
  <button type="submit">Log Out</button>
</form>
                            </div>
                        </div>
                    </a>
                </div>
            </li>

        </ul>
</nav>

{% if kanban  %}
    <div class="content-wrapper kanban">
{% else %}
    <div class="content-wrapper">
{% endif %}



<div class="content-header">
<div class="container">
<div class="row mb-2">
<div class="col-sm-6">
<h1 class="m-0"> {{title_pagina.0.title_card}} </h1>
</div>
<div class="col-sm-6">

{% if kanban  %}
      
         
            <form action="" method="get"  name="prodsubmit" >
            <div class="input-group mb-3">
                
                 <div class="input-group-prepend">
                    <button class="btn btn-outline-secondary dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Filtrar per estado </button>
                    <div class="dropdown-menu">
                        
                          <a class="dropdown-item" href="{% url 'myapp:pedidos_actualizados'%}?estado=espera_preparacion">En espera la preparación </a>
                           <a class="dropdown-item" href="{% url 'myapp:pedidos_actualizados'%}?estado=preparacion">En preparación </a>
                        
                    
                        <div role="separator" class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{% url 'myapp:pedidos_actualizados' %}">Mostrar tot</a>
                      </div>
                    </div>

                  <input type="text" name="codigo_pedido" class="form-control" placeholder="Escribe el codigo del pedido que desea buscar" value="{{ request.GET.codigo_pedido }}" autocomplete="off">
                  <a href="javascript:document.prodsubmit.submit()" style="text-decoration:none;">
                    <span class="input-group-text" id="basic-addon1">Buscar</span>
                  </a>

             </div>
        </form>

      
{% else %}

<ol class="breadcrumb float-sm-right">

      {% for item in ruta_pagina %}

          {% if item.button_text %}
           <a href="{% url item.link %}"><button class="btn btn-primary">{{ item.button_text }}</button></a>
         {% endif %}

            {% if item.link %}
        <li class="breadcrumb-item"><a href="{% url item.link %}?">{{ item.text }}</a></li>
            {% elif item.parametro %}
                <li class="breadcrumb-item"><a href="{{ item.parametro }}">{{ item.text }}</a></li>
            {% else %}
                <li class="breadcrumb-item active">{{ item.text }}</li>
            {% endif %}


     
      {% endfor %}



</ol>

{% endif %}
</div>
</div>
</div>
</div>



 {% block content %}
     
 {% endblock %}
</div>

{% if kanban  %}
     <footer class="main-footer" style="background-color: white" >
     {% block paginacion %}
    {% endblock %}
     </footer>
{% else %}
   <footer class="main-footer  py-4">
    <div class="container">
        <div class="row">
            <!-- Sobre nosotros -->
            
            <div class="col-md-2">
                 <img src="/media/img/icono_app.ico" width="200px" height="200px" alt="logotipo menu"  >
            </div>
            
            <div class="col-md-4">
                <h5>Sobre Nosotros</h5>
                <p style="color: #3f474e">
                    Somos una plataforma dedicada a ofrecer la mejor experiencia en entrega de comida. Nuestro objetivo es conectar a los usuarios con sus restaurantes cercanos de manera rápida y eficiente.
                </p>
            </div>

            <!-- Enlaces útiles -->
            <div class="col-md-2">
                <h5>Enlaces Útiles</h5>
                <ul class="list-unstyled">
                    <li><a href="#" class="text-black">Términos y Condiciones</a></li>
                    <li><a href="#" class="text-black">Política de Privacidad</a></li>
                </ul>
            </div>

            <!-- Contacto -->
            <div class="col-md-2">
                <h5>Contacto</h5>
                <p>
                    <i class="fas fa-map-marker-alt"></i> Calle 123, Lleida, España<br>
                    <i class="fas fa-phone"></i> +34 123 456 789<br>
                    <i class="fas fa-envelope"></i> info@delivereat.com
                </p>
            </div>

            <!-- Redes Sociales -->
            <div class="col-md-2">
                <h5>Síguenos</h5>
                <a href="#" class="text-black mr-3"><i class="fab fa-facebook-f"></i></a>
                <a href="#" class="text-black mr-3"><i class="fab fa-twitter"></i></a>
                <a href="#" class="text-black mr-3"><i class="fab fa-instagram"></i></a>
                <a href="#" class="text-black"><i class="fab fa-linkedin"></i></a>
            </div>
        </div>

        <div class="row">
            <div class="col-12 text-center">
                <p class="mb-0" style="color: #3f474e" >&copy; 2024 .</p>
                <p class="mb-0" style="color: #3f474e" >Desarrollado por <a href="https://github.com/TiberiuPaiu">Tiberiu Paiu </a>.</p>
            </div>
        </div>
    </div>
</footer>
{% endif %}
 
{% if kanban  %}
    </div>
{% else %}
   </div>
{% endif %}


 </div>


<!-- Script para enviar una solicitud POST al hacer clic en el enlace -->



{% block script %}


{% endblock %}
</body>