myapp/urls.py
from django.urls import path ,include
from rest_framework.routers import DefaultRouter

from myapp.views import *

from django.conf import settings
from django.conf.urls.static import static

from django.contrib.auth.views import LoginView, logout_then_login ,LogoutView



app_name = "myapp"
urlpatterns = [

    path('', CustomLoginView.as_view(), name='login'),
    path('registro/', post_registro, name='hacer_registro'),
    path('cliente/registro/', post_registro_cliente, name='hacer_registro_cliente'),


    path('logout/', LogoutView.as_view(), name='logout'),

    # DetalleGenerico
    path('detalle/<str:tipo_objeto>/<int:id_objeto>/', login_required(DetalleGenericoView.as_view()), name='detalle_generico'),


    path('historial/pedidos/restaurante/<int:restaurante_id>', login_required(ListPedidosAdmin.as_view()), name='historial_pedidos_restaurante'),
    #restaurante
    path('lista/restaurantes/', login_required(ArticleDetailView.as_view()), name='list_restaurantes'),
    path('anadir/restaurante/', login_required(post_add_restaurante), name='add_restaurante'),

    #user_repartidor_cocina
    path('anadir/trabajdor/repartidor/<int:restaurante_id>', login_required(add_user_reparidor), name='add_user_reparidor'  ),
    path('anadir/trabajdor/cocina/<int:restaurante_id>', login_required(add_user_cocina), name='add_user_cocina'  ),

    path('lista/trabajdores/<int:restaurante_id>', login_required(UsuariosRestauranteListView.as_view()), name='list_user_restaurant'),

    path('reset_password/<int:user_id>/<int:restaurante_id>/', login_required(reset_password), name='reset_password'),
    path('denegar_acceso/<int:user_id>/<int:restaurante_id>/', login_required(denegar_acceso), name='denegar_acceso'),
    #platos
    path('restaurante/agregar_plato/<int:restaurante_id>/', login_required(agregar_plato), name='agregar_plato'),
    path('restaurante/listar_plato/<int:restaurante_id>/', login_required(PlatosRestauranteListView.as_view()) , name='list_platos'),

    # resena
    path('resena/<str:tipo_objeto>/<int:id_objeto>/',  login_required(ResenasView.as_view()), name='resena_generico'),
    path('resena/crear/<str:tipo_objeto>/<int:id_objeto>/', login_required(crear_resena), name='crear_una_resena'),

    path('resena/<str:tipo_objeto>/<int:id_objeto>/admin/',  login_required(ResenasAdminView.as_view()), name='resena_generico_admin'),

    path('resenas/<str:tipo_objeto>/<int:id_objeto>/borrar/<int:pk>/', login_required(BorrarResenaView.as_view()), name='borrar_resena'),

    #horarios res
    path('restaurante/add_horarios/<int:restaurante_id>/', login_required(add_horarios), name='add_horarios'),



    #admins
    path('lista/partners', PartnersListView.as_view(),  name='list_partners' ),
    path('acces/partners/<int:id_user>/', active_partners,name='active_partners'),


    #cliente
    path('cliente/lista/restaurantes/', login_required(RestauranteListClienteView.as_view()), name='restaurantes_list_cliente'),
    path('cliente/lista/restaurante/<int:restaurante_id>/platos/', login_required(PlatosListClienteView.as_view()), name='platos_list_cliente'),


    #cliente-carito
    path('agregaralcarrito/<int:plato_id>/', login_required(agregar_al_carrito), name='agregar_carrito'),
    path('carrito/',  login_required(carrito_lista), name='pagina_del_carrito'),
    path('quitar_plato_carrito/<int:plato_id>/', login_required(quitar_plato_carrito),
         name='quitar_plato_carrito'),

    path('eliminar/plato/carrito/<int:plato_id>/',  login_required(eliminar_plato_carrito), name='eliminar_plato_carrito'),
    path('carrito/borrar/', login_required(borrar_carrito), name='borrar_carrito'),

    #pedidos
    path('pedidos_realizados/', login_required(Pedidos_realizadosView.as_view()) , name='pedidos_realizados'),
    path('pedido/<int:pedido_id>/cancelar/', login_required(cancelar_pedido), name='cancelar_pedido'),
    path('procesar_pedido/form/', login_required(procesar_pedido_from), name='procesar_pedido_form'),



    #cocina
    path('pedidos_actualizados/', login_required(ListPedidosCocina.as_view()), name='pedidos_actualizados'),
    path('pedido/<int:pedido_id>/preparacion/', login_required(preparacion_pedido), name='preparacion_pedido'),
    path('asignar_repartidor/<int:pedido_id>', asignar_repartidor, name='asignar_repartidor'),

    #repartidor
    path('pedidos/para/<str:tipo_objeto>/', login_required(ListPedidosRepartidor.as_view()), name='pedidos_repartidor'),
    #path('pedidos/para/entregar/', login_required(ListPedidosRepartidor.as_view()), name='pedidos_para_entregar'),
    #path('pedidos/entregados/', login_required(ListPedidosParaRecoger.as_view()), name='pedidos_para_recoger'),
    path('pedidos/<int:pedido_id>/recoger_pedido/', login_required(recoger_pedido), name='recoger_pedido'),
    path('pedido/<int:pk>/map', login_required(Map_Rpartidor.as_view()), name='map_rpartidor'),
    path('pedidos/<int:pedido_id>/validar_pedido/', login_required(validar_pedido), name='validar_pedido'),


    path('generar/<int:id_objeto>/<str:tipo_objeto>/pdf', login_required(Generar_pdf.as_view()),name='generar_pdf'),

    path('estado_pedido/<int:pedido_id>/actualizo/', EstadoPedidoActualizado.as_view(), name='estado_pedido_actualizado'),


]

# Agregar la configuracion para servir archivos de medios
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# add Configuring static files
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

sistemdelivereat/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('myapp.urls')),

]

# Agregar la configuracion para servir archivos de medios

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# add Configuring static files
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

myapp/views/cliente.py
from datetime import datetime
from decimal import Decimal

import stripe
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.paginator import Paginator
from django.db import transaction
from django.db.models import Avg, Q, Subquery, OuterRef, Sum
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import ListView, DetailView
from django.db.models import F, ExpressionWrapper, DecimalField
from django.db.models.functions import Round, Cast
from myapp.models import Restaurante, Plato, Cliente, Pedido, Ubicacion, TipoComida, PedidoPlato
from sistemdelivereat.utils.OpenStreetMap import Geocoder
from sistemdelivereat.utils.RolRequiredMixin import RolRequiredMixin
from sistemdelivereat.utils.carito_copras import CarritoDeCompras
from sistemdelivereat.utils.decorators import web_access_type_required
from django.contrib.auth.decorators import login_required

from django.contrib import messages

stripe.api_key = 'sk_test_51PMYfiGF2SGr9v2Ept70FwVCMRnjM8pdznzqezNqqxb3nmOx2xKFV9tezdmUONwHliygMlXXIFejCtvSdaIs2Hmg00AbvQ91MU'


class RestauranteListClienteView(LoginRequiredMixin, RolRequiredMixin, ListView):
    model = Restaurante
    user_type_required = ['cliente']
    template_name = 'cliente/lista_restaurantes.html'
    context_object_name = 'restaurantes'
    paginate_by = 10

    def get_queryset(self):
        cliente_ciudad=get_object_or_404(Cliente, user=self.request.user).ubicacion.ciudad
        restaurantes = Restaurante.objects.filter(ubicacion__ciudad=cliente_ciudad).annotate(
            puntuacion_media=Avg('resenas__puntuacion')
        ).order_by('-puntuacion_media')



        query = self.request.GET.get('query')

        if query:
            restaurantes = restaurantes.filter(
                Q(nombre=query) |
                Q(ubicacion__direcion__icontains=query)

            )
        return restaurantes

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context['title_pagina'] = {'label_title': "Llistado de restaurantes",
                                   'title_card': "Llistado de restaurantes " ,
                                   },



        return context


class PlatosListClienteView(LoginRequiredMixin, RolRequiredMixin, ListView):
    model = Plato
    user_type_required = ['cliente']
    template_name = 'cliente/lista_platos.html'
    context_object_name = 'platos'
    paginate_by = 10


    def get_queryset(self):
        restaurante_id = self.kwargs['restaurante_id']

        order_by = self.request.GET.get('order_by')
        order_direction = self.request.GET.get('order_direction')
        precio_min = self.request.GET.get('precio_min')
        precio_max = self.request.GET.get('precio_max')

        if precio_min and precio_max:
            try:
                precio_min = float(precio_min)
                precio_max = float(precio_max)
                if precio_min > precio_max:
                    messages.error(self.request, 'El precio mínimo no puede ser mayor que el precio máximo.')
                    return Plato.objects.none()
            except ValueError:
                messages.error(self.request, 'Los valores de precio deben ser números válidos.')
                return Plato.objects.none()

        platos = Plato.objects.filter(restaurante_id=restaurante_id).annotate(
            puntuacion_media=Avg('resenas__puntuacion'),
            precio_final=(F('precio') - (F('precio') * F('descuento') / 100))
        )

        if order_by == "precio":
            if order_direction == "asc":
                platos = platos.order_by('precio_final')
            elif order_direction == "desc":
                platos = platos.order_by('-precio_final')
        else:
            platos = platos.order_by('-puntuacion_media')

        if precio_min:
            platos = platos.filter(precio_final__gte=precio_min)
        if precio_max:
            platos = platos.filter(precio_final__lte=precio_max)

        query = self.request.GET.get('query')
        tipo_comida = self.request.GET.get('tipo_comida')
        if query:
            platos = platos.filter(
                Q(nombre__icontains=query)

            )
        if tipo_comida:
            platos = platos.filter(
                Q(tipo_comida__nombre=tipo_comida)

            )
        return platos


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Obtén el ID del restaurante de la URL
        restaurante_id = self.kwargs['restaurante_id']

        context['tipos_comida'] = TipoComida.objects.filter(platos_tipo_comida__in=self.get_queryset()).distinct()

        # Obtén el restaurante
        restaurante = Restaurante.objects.get(pk=restaurante_id)

        context['title_pagina'] = {'label_title': "Llistat de platos",
                                   'title_card': "Llistat de platos de " + restaurante.nombre,
                                   },
        context['ruta_pagina'] = [{
            'text': "Lista de restaurantes",
            'link': "myapp:restaurantes_list_cliente",
        },
            {
                'text': "Lista de los platos  de " + restaurante.nombre,
                'link': "",
            }
        ]
        context['restaurante_id'] = restaurante.id
        return context

def descuento(plato):
    precio_con_descuento = plato.precio * (1 - Decimal(str(plato.descuento)) / 100)
    return precio_con_descuento.quantize(Decimal('0.00'))
def tax(precio):
    precio_con_tax = precio + ((precio * 10 ) / 100 ) + ((precio * 3 ) / 100 )
    return precio_con_tax.quantize(Decimal('0.00') + Decimal('0.50') )
@login_required
@web_access_type_required("cliente")
def agregar_al_carrito(request, plato_id):
    carrito = CarritoDeCompras(request)
    carrito.agregar_plato(str(plato_id))
    return redirect(request.META.get('HTTP_REFERER', '/'))


@login_required
@web_access_type_required("cliente")
def carrito_lista(request):
    carrito = CarritoDeCompras(request).obtener_carrito()
    platos_en_carrito = Plato.objects.filter(id__in=carrito.keys())


    # Verificar si el carrito está vacío
    if not platos_en_carrito:
        total_formateado = Decimal('0.00')
        totales_por_restaurante = {}
    else:
        # Calcular el total por restaurante
        totales_por_restaurante = {}
        for plato in platos_en_carrito:
            restaurante_id = plato.restaurante.id
            plato_id = str(plato.id)
            cantidad = carrito.get(plato_id, {'cantidad': 0})['cantidad']
            precio_final = descuento(plato)

            if restaurante_id not in totales_por_restaurante:
                totales_por_restaurante[restaurante_id] = {
                    'nombre': plato.restaurante.nombre,
                    'total': 0
                }

            totales_por_restaurante[restaurante_id]['total'] += cantidad * precio_final

        # Calcular el total general
        total_general = sum(tax(restaurante['total']) for restaurante in totales_por_restaurante.values())
        total_formateado = Decimal(str(total_general)).quantize(Decimal('0.01'))

    # Crear un diccionario para almacenar las cantidades de cada plato en el carrito
    cantidades_por_plato = {}
    for plato in platos_en_carrito:
        plato_id = str(plato.id)
        cantidad = carrito.get(plato_id, {'cantidad': 0})['cantidad']
        cantidades_por_plato[plato_id] = cantidad


    title_pagina = [
        {'label_title': "Carrito de compras",
         'title_card': "Carrito de compras "}
    ]
    ruta_pagina = [
        {'text': "Lista de restaurantes", 'link': "myapp:restaurantes_list_cliente"},
        {'text': "Carrito de compras", 'link': ""}
    ]

    return render(request, 'cliente/carito/carrito_lista.html', {
        'platos': platos_en_carrito,
        'cantidades_por_plato': cantidades_por_plato,
        'total': total_formateado,
        'totales_por_restaurante': totales_por_restaurante,
        'title_pagina': title_pagina,
        'ruta_pagina': ruta_pagina,
    })
@login_required
@web_access_type_required("cliente")
def eliminar_plato_carrito(request, plato_id):
    carrito = CarritoDeCompras(request)
    carrito.eliminar_plato(str(plato_id))
    return redirect('myapp:pagina_del_carrito')


@login_required
@web_access_type_required("cliente")
def quitar_plato_carrito(request, plato_id):
    carrito = CarritoDeCompras(request)
    carrito.quitar_plato(str(plato_id))
    return redirect('myapp:pagina_del_carrito')


@login_required
@web_access_type_required("cliente")
def borrar_carrito(request):
    carrito = CarritoDeCompras(request)
    carrito.borrar_carrito()
    return redirect('myapp:pagina_del_carrito')





class Pedidos_realizadosView(LoginRequiredMixin, RolRequiredMixin, ListView):
    model = Pedido
    user_type_required = ['cliente']
    template_name = 'cliente/pedido/listado_pedidos.html'
    context_object_name = 'pedidos'
    paginate_by = 10


    def get_queryset(self):
        page_number = self.request.GET.get('page', 2)
        pedidos = Pedido.objects.filter(cliente=Cliente.objects.get(user = self.request.user )).order_by('-fecha_pedido')
        query = self.request.GET.get('query')
        estado_pedido = self.request.GET.get('estado')
        restaurante = self.request.GET.get('restaurante')
        data_inicio = self.request.GET.get('data_inicio')
        data_fin = self.request.GET.get('data_fin')

        if query:
            pedidos = pedidos.filter(
                Q(platos__nombre__icontains=query)
                # Q(codigo_pedido=query)
            )
        if estado_pedido:
            pedidos = pedidos.filter(
                Q(estado=estado_pedido)
            )
        if restaurante:
            pedidos = pedidos.filter(
                Q(restaurante_id=restaurante)
            )
        if data_inicio and data_fin:

templates/cliente/carito/carrito_lista.html
{% extends 'base/base_adminlte.html' %}
{% load static %}
{% load custom_filters %}

{% block style %}
 <link rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="{% static 'adminlte/css/all.min.css' %}">
    <!--  iconas fas -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css"
          integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">

    <link rel="stylesheet" href="{% static 'adminlte/css/adminlte.min.css' %}">
{% endblock %}

{% block content %}
<div class="content">


<div class="container">

   <div class="row">



        <div class="col-md-9">


  <div class="card">

   <div class="card-body">

        <table class="table table-bordered" width="900px" border="0" cellspacing="0" cellpadding="0">
                    <thead>
                        <tr>

                            <th>Nombre</th>
                            <th>Restaurante</th>
                            <th>Precio</th>
                            <th>Cantidad</th>
                            <th>Opción</th>
                        </tr>
                    </thead>
                    <tbody>
                     {% if platos %}
                    {% for plato in platos %}


                     <tr>

                            <td>
                                <img class="img-circle img-bordered-sm" src="{{ plato.imagen.url }}" alt="user image" width="20%" height="20%" >

                                {{ plato.nombre }}

                            </td>
                      <td>{{ plato.restaurante.nombre }}</td>
                            <td>
                                 {% if plato.descuento > 0 %}
            <del>{{ plato.precio }}</del> -  {{ plato|descuento }}  € Descuento : {{ plato.descuento }}%

            {% else %}
               {{ plato.precio }}  €
            {% endif %}


                            </td>
                            <td>
                                <a href="{% url 'myapp:quitar_plato_carrito' plato_id=plato.id %}">  <button type="button" class="btn btn-sm btn-warning" onclick="">-</button></a>
                            {{ cantidades_por_plato|custom_get:plato.id }}
                             <a href="{% url 'myapp:agregar_carrito' plato_id=plato.id %}"><button type="button" class="btn btn-sm btn-warning" onclick="">+</button></a>
                            </td>
                             <td>
                                 <a href="{% url 'myapp:eliminar_plato_carrito' plato_id=plato.id %}"> <button type="button" class="btn btn-sm btn-danger" >Eliminar</button></a>
                             </td>

                       </tr>

                    {% endfor %}

                     {% else %}
                                    <tr>
                                        <td colspan="5">No hay elementos en el carrito</td>
                                    </tr>
                                {% endif %}
                </tbody>
        </table>
    </div>
  </div>



        </div>
   <div class="col-md-3 d-flex align-items-center">

                   <div class="card">
                        <div class="card-body">
                        <!-- Contenido del menú lateral -->
                        
   {% for restaurante_id, data in totales_por_restaurante.items %}                    
<p class="lead">Restaurante : {{ data.nombre }}</p>
<div class="table-responsive">
<table class="table">
<tr>
<th style="width:60%">Subtotal:</th>
<td>{{ data.total}}  €</td>
</tr>
<tr>
<th>Impuesto Plataforma (10%)</th>
<td>{{  data.total|tax_plat}}  €  </td>
</tr>
<tr>
<th>Impuesto Traferencias (3% + 0,50€):</th>
<td>{{  data.total|tax_trans}} €  </td>
</tr>
<tr>
<th>Total:</th>
<td>{{  data.total|tax_full}} €  </td>
</tr>
</table>
</div>
{% endfor %}
  <p class="lead">Total : {{ total }} € </p>                      
      
                         {% if platos %}
                             <a href="{% url 'myapp:borrar_carrito' %}"><button type="button" class="btn btn-sm btn-danger">Borrar Carrito</button></a>
                            <a  href="{% url 'myapp:procesar_pedido_form'%}" >  <button type="button " class="btn btn-sm btn-primary" >Realizar Pedido</button> </a>

                         {% endif %}
                             </div>
                   </div>

         </div>
    </div>



</div>
</div>


{% endblock %}


{% block script %}

<!-- jQuery -->
<script src="{% static 'adminlte/js/jquery.min.js' %}"></script>
<!-- Bootstrap 4 -->
<script src="{% static 'adminlte/js/bootstrap.bundle.min.js' %}"></script>
<!-- AdminLTE App -->
<script src="{% static 'adminlte/js/adminlte.min.js' %}"></script>

{% endblock %}